org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=5
org.gradle.parallel=true
org.gradle.console=rich

mod.group=com.bawnorton
mod.id=integrationfixes
mod.name=Integration Fixes
mod.version=1.2.0
mod.author=Bawnorton
mod.license=MIT
mod.description=Fixes for the Integrated Minecraft modpack

publishing.curseforge=1278371